### ISSUE TITLE
This app is not compatible with your system.

### ISSUE THREAD

**Issue by VergeDX** [dawndiy/shadowsocks-ubuntu#3]
I can't search this app in OpenStore, and I open it on browser to go to Store, it says:
"This app is not compatible with your system."
My device is Nexus 5 with Ubuntu Touch 16.04.
@dawndiy

**Comment by dawndiy** [comment]
The App in OpenStore built with framework ubuntu-sdk-15.04.4 . You can try build it using the source code for your system.

**Comment by VergeDX** [comment]
Got it.
